name: Discord Release Webhook

on:
  workflow_dispatch:

jobs:
  get-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get current tag
        id: current_tag
        run: |
          echo "CURRENT_TAG=$(git describe --abbrev=0 --tags") >> $GITHUB_OUTPUT

      - name: Get previous tag
        id: previous_tag
        run: |
          echo "PREVIOUS_TAG=$(git describe --abbrev=0 --tags --exclude='*-beta*' --exclude='$(git describe --abbrev=0 --tags)')" >> $GITHUB_OUTPUT

      - name: Get changelog
        id: changelog
        run: |
          echo "CHANGELOG=$(git shortlog --no-merges --reverse '${{ steps.previous_tag.outputs.PREVIOUS_TAG }}..${{ steps.current_tag.outputs.CURRENT_TAG }}')" >> $GITHUB_OUTPUT
          

  discord-release-notification:
    runs-on: ubuntu-latest
    needs: get-changelog

    env:
      TITLE: "PermoksAccountManager Release"

    steps:
      - name: Test
        id: test
        run: |
          echo "${{ needs.get-changelog.steps.current_tag.outputs.CURRENT_TAG }}"
          
      - name: Send Discord Notification
        id: discord
        uses: tsickert/discord-webhook@v6.0.0
        if: success()
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-title: ${{ env.TITLE }}
          embed-url: https://github.com/Lardeck/PermoksAccountManager/releases/latest
          embed-description: ${{ needs.get-changelog.steps.changelog.outputs.CHANGELOG }}
