name: Post Release Changelog To Discord

on:
  workflow_dispatch:

jobs:
  get-changelog:
    runs-on: ubuntu-latest

    outputs:
      current: ${{ steps.current_tag.outputs.tag}}
      previous: ${{ steps.previous_tag.outputs.tag }}
      changelog: ${{ steps.changelog.outputs.changelog}}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get current tag
        id: current_tag
        run: |
          echo "tag=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT

      - name: Get previous tag
        id: previous_tag
        run: |
          echo "tag=$(git describe --abbrev=0 --tags --exclude='*-beta*' --exclude='${{ steps.current_tag.outputs.CURRENT_TAG }}')" >> $GITHUB_OUTPUT

      - name: Get changelog
        id: changelog
        run: |
          echo "changelog=$(git log --pretty=format:'- %s' ${{ steps.previous_tag.outputs.PREVIOUS_TAG }}..${{ steps.current_tag.outputs.CURRENT_TAG }})" >> $GITHUB_OUTPUT

  post-changelog:
    runs-on: ubuntu-latest
    needs: get-changelog
    
    steps:
      - name: Send Discord Notification
        id: discord
        uses: tsickert/discord-webhook@v6.0.0
        if: success()
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-title: "PermoksAccountManager Release - ${{ needs.get-changelog.outputs.current }}"
          embed-url: https://github.com/Lardeck/PermoksAccountManager/releases/latest
          embed-description: ${{ needs.get-changelog.outputs.changelog }}
