name: Discord Release Webhook

on:
  workflow_dispatch:

jobs:
  get-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch release info
        id: get_release
        run: |
          release_info=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest)
          echo "::set-output name=release_info::${release_info}"

  discord-release-notification:
    runs-on: ubuntu-latest
    needs: get-changelog

    env:
      TITLE: "PermoksAccountManager Release"

    steps:
      - name: Send Discord Notification
        id: discord
        uses: tsickert/discord-webhook@v6.0.0
        if: success()
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-title: ${{ env.TITLE }}
          embed-url: https://github.com/Lardeck/PermoksAccountManager/releases/latest
          embed-description:  ${{needs.get_changelog.outputs.release_info.body}}
